### ISSUE TITLE
kubectl version 변경

### ISSUE THREAD

**Issue by dasomel** [K-PaaS/cp-deployment#1]
안녕하세요. OPA 리더 이기하입니다.

아래 kubectl 설치 스크립트가 있습니다.
현재 v1.5.1 버전에서는 1.28.6로 설치가 되는 데 아래 스크립트로 kubectl 버진이 1.27.5로 설치됩니다.
(ansible host으로 사용하는 master의 첫번째 노드)
https://github.com/K-PaaS/cp-deployment/blob/master/single/roles/kubectl/tasks/main.yml

- name: Download kubectl binary
  shell: curl -LO "https://dl.k8s.io/release/v1.27.5/bin/linux/amd64/kubectl"

-> 수정 요청: 1.27.5 -> 1.28.6

검토 요청 드립니다.
고맙습니다.

**Comment by dev-taewoo** [comment]
안녕하세요.

Control Plane 첫번째 노드에 설치되는 kubectl 버전이 1.27.5 -> 1.28.6 으로 변경되었습니다.
변경사항은 v.1.5.1.1에 적용되었습니다.

감사합니다.
