### ISSUE TITLE
CVE :: X.509 Certificate Subject CN Does Not Match the Entity Name

### ISSUE THREAD

**Issue by suslmk-lee** [K-PaaS/cp-deployment#2]
상반기 CVE/CCE 점검 중 etcd 인증서에 대한 이슈가 발생되었습니다.

Port 2379 
X.509 Certificate Subject CN Does Not Match the Entity Name

관련 내용 검토 해주십시오.

**Comment by dev-taewoo** [comment]
ETCD 버전이 변경됨에 따라 의존관계의 golang 버전이 함께 증가하여
적용되는 TLS 버전이 1.2 -> 1.3으로 변경, 인증서에 대한 이슈가 발생하였습니다.

ETCD의 TLS 버전을 1.2로 적용하여 관련 이슈 처리하였으며 v1.5.1.1에 적용되었습니다.
