### ISSUE TITLE
K-PaaS 플랫폼 PSS(Pod Security Standards) 적용여부

### ISSUE THREAD

**Issue by soyoung1122** [K-PaaS/cp-deployment#3]
K-PaaS 플랫폼에 PSS 가 적용되어 있나요 ?

**Comment by jinhyojin** [comment]
Policy-as-Code(PaC) 수명 주기를 관리하기 위해 Kyverno 프로젝트가 도입되었으며, 
K-PaaS 컨테이너 플랫폼 v1.6.0 부터 PSS가 기본 적용 되었습니다. 
자세한 사항은 [Releases v1.6.0](https://github.com/K-PaaS/cp-deployment/releases/tag/v1.6.0) 를 참고 부탁드립니다.
