### ISSUE TITLE
K-PaaS 플랫폼 네임스페이스 격리

### ISSUE THREAD

**Issue by soyoung1122** [K-PaaS/cp-deployment#5]
K-PaaS 플랫폼에 네임스페이스 간 네트워크 격리가 가능한가요 ?

**Comment by jinhyojin** [comment]
K-PaaS 컨테이너 플랫폼 v1.6.0 부터 각 네임스페이스 별 네트워크 격리가 가능합니다. 
Kyverno 정책을 적용하여 구성되었으며, portal을 통해 네임스페이스를 공유할 수 도 있습니다.
이 정책은 [Releases v1.6.0](https://github.com/K-PaaS/cp-deployment/releases/tag/v1.6.0)부터 적용되며, 자세한 사항은 [deploy-cp-kyverno-policy](https://raw.githubusercontent.com/K-PaaS/cp-deployment/refs/heads/master/applications/kyverno-1.12.5/deploy-cp-kyverno-policies.sh) 를 참고 부탁드립니다.
